### PR TITLE
Team 030 frontend arkson

### PR DESCRIPTION
**Pull request by josiaharkson**
# Changes
- The name o the frontend live link deployed on heroku has been changed
- `.env` `eslint.js` file has been updated

### CODE REVIEW

**Comment by kingsley-einstein** [comment]
There was no need to skip preflight check as the backend already allows CORS and sets preflight for all origins but still a good job. 
Please ensure you wait a bit till we get a UI or design pattern for the app. We have settled for MDBootstrap as the css library we'd be leveraging. I'll approve this PR soon.

**Review by jan-far — APPROVED** [review]
Checked

**Review by kingsley-einstein — APPROVED** [review]
Approved!

**Comment by josiaharkson** [comment]
> There was no need to skip preflight check as the backend already allows CORS and sets preflight for all origins but still a good job.
> Please ensure you wait a bit till we get a UI or design pattern for the app. We have settled for MDBootstrap as the css library we'd be leveraging. I'll approve this PR soon.

Okay! Thanks bro
Material UI is completely free (100%), complete package, no premuim components and as such you have full access to all of its UI component compared to MDBootstrap.
Material UI has better community support than MDBootstrap which gives us advantage. Not withstanding though, it all comes down to implementing a UI design and which css framework will suit us better. While we wait for the design pattern you guys could go through Material UI docs and see through!

**Pull request merged**
